/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BASEDCHAT_H_RPCGEN
#define _BASEDCHAT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PROGRAMA_CHAT 0x20000001
#define VERSION_CHAT 1

#if defined(__STDC__) || defined(__cplusplus)
#define write 1
extern  int * write_1(char **, CLIENT *);
extern  int * write_1_svc(char **, struct svc_req *);
#define getChat 2
extern  char ** getchat_1(void *, CLIENT *);
extern  char ** getchat_1_svc(void *, struct svc_req *);
extern int programa_chat_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define write 1
extern  int * write_1();
extern  int * write_1_svc();
#define getChat 2
extern  char ** getchat_1();
extern  char ** getchat_1_svc();
extern int programa_chat_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BASEDCHAT_H_RPCGEN */
