/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include <stdio.h>
#include <unistd.h>
#include <string.h>
#include <pthread.h>
#include <ncurses.h>
#include "basedChat.h"			/* basedChat.h generated by rpcgen */

CLIENT *clnt;
WINDOW *input_win, *chat_win;

void 
*threadFunc ()
{
	char **result_2;
	char *getchat_1_arg;
	
	result_2 = getchat_1((void*)&getchat_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
		exit (1);
	}
	mvwprintw(chat_win, 1, 1, *result_2);
	wrefresh(chat_win);

	while(1)
	{
		sleep(1);

		result_2 = getchat_1((void*)&getchat_1_arg, clnt);
		if (result_2 == (char **) NULL) {
			clnt_perror (clnt, "call failed");
		}
		mvwprintw(chat_win, 1, 1, *result_2);
		wrefresh(chat_win);
	}
}

int
main (int argc, char *argv[])
{
	char *host;
	char *nickname;
	int  *result_1;
	char* write_1_arg = (char*)malloc(sizeof(char));
	char buffer2[100];

	if (argc != 3) {
		printw ("usage: %s server_host\n", argv[1]);
		refresh();
		exit (1);
	}

	host = argv[1];
	nickname = argv[2];

	initscr();	/* Start curses mode */

	clnt = clnt_create (host, PROGRAMA_CHAT, VERSION_CHAT, "udp");
	if (clnt == (CLIENT *)NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	printw ("....... Welcome %s!\n", nickname);
	refresh();

	chat_win = newwin(15, 40, 9, 40);			/* Creating a Window */
	input_win = newwin(1, 100, 2, 9);			/* Creating a Window */
	box(chat_win, 0, 0);						/* making box border with default border styles */
    mvwprintw(chat_win, 0, 1, "CHAT");			/* move and print in window */
	wrefresh(chat_win);
	wrefresh(input_win);

	pthread_t h1 = pthread_create(&h1, NULL, threadFunc, NULL);

	while (1)
	{
		printw ("%s%s", nickname, " --> ");
		refresh();

		getstr(write_1_arg);
		strcat(strcpy(buffer2, nickname), ": ");
		strcat(buffer2, write_1_arg);
		strcat(buffer2, "\n");
		strcpy(write_1_arg, buffer2);
	
		result_1 = write_1(&write_1_arg, clnt);
		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
			exit (1);
		}
	}

	clnt_destroy (clnt);
	//close(h1);
	endwin();	/* End curses mode */

	exit (0);
}